### ISSUE TITLE
re:一点儿悖论

### ISSUE THREAD

**Issue by PuRonglong** [catbaron0/blog#3]
想到了那个理发师悖论，哈哈，
“我将为本城所有不给自己刮脸的人刮脸，我也只给这些人刮脸。我对各位表示热诚欢迎！”
在把玩文字时更想知道，悖论在实际中可以有什么作用吗？

**Comment by catbaron0** [comment]
23333，我也不知道。不过我觉得构造悖论是一种幽默的能力吧。

**Comment by PuRonglong** [comment]
同意[握爪]
