### ISSUE TITLE
🥺

### ISSUE THREAD

**Issue by suoge227** [catbaron0/blog#4]
![1](https://github.com/user-attachments/assets/b8228515-20fa-4533-8fd6-ea7487fd928d)
你好，我想实现微博内容迁移，但是出现了上面图片中的问题，我该如何解决呢？🥺

**Comment by catbaron0** [comment]
你好，因为我的微博已经无法使用了，所以我没办法做详细的测试。
不过本身这个脚本依赖的是远古时期手机网页版本的登陆接口，所以很可能是这个接口本身失效了。
